# net6filter-rules.conf IPv6

# we allow everything on these interfaces
# (space separated)
all="lo"
# ping is allowed on these interfaces
ping="net0"
# more specifically by protocol, by interface and by port
tcpint="net0+22"
udpint=""
# except for anything that comes from these networks
exceptions=""
# DROP or REJECT
deny_action="DROP"
# log packets denied?
logdeny="False"
# execute extra iptables commands
extra_rules=()
#("-A INPUT -p TCP --dport 80 -j ACCEPT" "-A INPUT -p TCP --dport 443 -j ACCEPT")
# gateway configuration
gateway="False"
# Enable masquerade for IPv6
masquerade="True"
# external interface
extif="net0"
# internal interface
intif="net1"
