#!/usr/bin/env bash

set -o pipefail # trace ERR through pipes
set -o errtrace # trace ERR through 'time command' and other functions
set -o errexit # exit the script if any statement returns a non-true return value

nf_conf_dir="/etc/netfilter-rules"
dry_run=false
verbose=false

if [ -t 1 ] ; then
  col_yellow='\033[0;33m'
  col_cyan='\033[0;36m'
  col_reset='\033[0m'
else
  col_yellow=''
  col_cyan=''
  col_reset=''
fi

die() {
  echo -e "${1}"
  exit 1
}

run() {
  if "${dry_run}" ; then
    ( IFS=' '; echo -e "${col_yellow}[dry-run]${col_reset} $*" )
  else
    if "${verbose}" ; then
      ( IFS=' '; echo -e "${col_cyan}[verbose]${col_reset} $*" )
      "$@" | sed "s/^/$(printf "${col_cyan}[verbose]${col_reset} ")/"
    else
      "$@"
    fi
  fi
}

usage() {
  echo -e "ex.: ${0} ipv(4|6) apply [--dry-run] [--verbose]"
  echo -e "ex.: ${0} ipv(4|6) flush [--dry-run] [--verbose]"
  echo -e "ex.: ${0} ipv(4|6) status"
  exit 1
}

check_user_is_root() {
  if [ "$(id -u)" -ne 0 ] ; then
    die "!Please run as root or using doas/sudo!"
  fi
}

source_conf_file() {
  local nf_conf
  nf_conf="${nf_conf_dir}"/"${1}".conf
  [ ! -d "${nf_conf_dir}" ] && {
    die "${nf_conf_dir} directory missing"
  }
  [ ! -f "${nf_conf}" ] && {
    die "${nf_conf} missing"
  }
  source "${nf_conf}"
}

apply_extra_rules() {
  local extra_rule
  for extra_rule in "${extra_rules[@]}" ; do
    run ${iptables_bin} ${extra_rule}
  done
}

flush() {
  run ${iptables_bin} -P INPUT ACCEPT
  run ${iptables_bin} -P OUTPUT ACCEPT
  run ${iptables_bin} -P FORWARD ACCEPT
  run ${iptables_bin} -F INPUT
  run ${iptables_bin} -F OUTPUT
  run ${iptables_bin} -F FORWARD
  run ${iptables_bin} -F PREROUTING -t nat
  run ${iptables_bin} -F PREROUTING -t mangle
  run ${iptables_bin} -F POSTROUTING -t nat
  run ${iptables_bin} -F POSTROUTING -t mangle
  run ${iptables_bin} -F LOGDENY -t filter 2>/dev/null || true
  run ${iptables_bin} -X LOGDENY -t filter 2>/dev/null || true
}

create_log_rule() {
  run ${iptables_bin} -N LOGDENY
  run ${iptables_bin} -t filter -A LOGDENY -j LOG --log-prefix "[${deny_action}] "
  run ${iptables_bin} -t filter -A LOGDENY -j "${deny_action}"
  run ${iptables_bin} -t filter -A INPUT -j LOGDENY
}

loop_icmp() {
  local icmp int
  icmp="icmp"
  if [ "${1}" == "ipv6" ] ; then
    icmp="${1}-${icmp}"
  fi
  for int in ${ping} ; do
    run ${iptables_bin} -A INPUT -p ${icmp} -i ${int} -j ACCEPT
  done
}

loop_except() {
  local except
  for except in ${exceptions} ; do
    run ${iptables_bin} -t filter -A INPUT -s ${except} -j ACCEPT
  done
}

loop_int_all() {
  local int_all
  for int_all in ${all} ; do
    run ${iptables_bin} -t filter -A INPUT -i ${int_all} -j ACCEPT
  done
}

loop_int_dport() {
  case "${2}" in
    tcpint)
      proto="TCP"
      proto_int="${tcpint}"
    ;;
    udpint)
      proto="UDP"
      proto_int="${udpint}"
    ;;
  esac
  OLDIFS=$IFS
  for int in ${proto_int} ; do
    IFS="+"
    set -- ${int}
    int=${1}
    shift
    nport=$#
    i=0;
    while (( ${i} < ${nport} )) ; do
      run ${iptables_bin} -t filter -A INPUT -i ${int} -p ${proto} --dport ${1} -j ACCEPT
      shift
      i=$(( i + 1 ))
    done
  done
  IFS=$OLDIFS
}

status() {
  ${iptables_bin} -L -n -v --line-numbers
}
set_conntrack() {
  run ${iptables_bin} -t filter -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
}

set_gateway() {
  if [ "${1}" == "ipv4" ] || [ "${masquerade}" == "True" ] ; then
    run ${iptables_bin} -t nat -A POSTROUTING -o ${extif} -j MASQUERADE
  fi
  run ${iptables_bin} -A FORWARD -i ${intif} -o ${extif} -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT
  run ${iptables_bin} -A FORWARD -o ${intif} -i ${extif} -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  "${dry_run}" || echo 1 > /proc/sys/net/${1}/conf/all/forwarding
}

default_deny() {
  if [ "${deny_action}" == "REJECT" ] ; then
    run ${iptables_bin} -A INPUT -p TCP -j "${deny_action}" --reject-with tcp-reset
    if [ "${1}" == "ipv6" ] ; then
      run ${iptables_bin} -A INPUT -p UDP -j "${deny_action}" --reject-with icmp6-port-unreachable
      run ${iptables_bin} -A INPUT -p ipv6-icmp -j "${deny_action}" --reject-with icmp6-adm-prohibited
    else
      run ${iptables_bin} -A INPUT -p UDP -j "${deny_action}" --reject-with icmp-port-unreachable
    fi
    run ${iptables_bin} -A INPUT -j "${deny_action}"
  else
    run ${iptables_bin} -A INPUT -j "${deny_action}"
  fi
}

main() {
  check_user_is_root
  [[ "${3:-}" == "--dry-run" ]] && dry_run=true
  [[ "${3:-}" == "--verbose" ]] && verbose=true
  case "${1}" in
    ipv4)
      if [ "$(basename ${0})" == "netfilter-rules-nft" ] ; then
        iptables_bin="$(command -v iptables-nft)"
      else
        iptables_bin="$(command -v iptables)"
      fi
    ;;
    ipv6)
      if [ "$(basename ${0})" == "netfilter-rules-nft" ] ; then
        iptables_bin="$(command -v ip6tables-nft)"
      else
        iptables_bin="$(command -v ip6tables)"
      fi
    ;;
    *)
      usage
    ;;
  esac
  case "${2}" in
    apply)
      source_conf_file "${1}"
      flush
      set_conntrack "${1}"
      loop_icmp "${1}"
      loop_except
      loop_int_all
      loop_int_dport "${1}" "tcpint"
      loop_int_dport "${1}" "udpint"
      apply_extra_rules
      [[ "${gateway}" == "True" ]] && set_gateway "${1}"
      [[ "${logdeny}" == "True" ]] && create_log_rule
      default_deny "${1}"
    ;;
    status)
      status
    ;;
    flush)
      source_conf_file "${1}"
      flush
    ;;
    *)
      usage
    ;;
  esac
}

main "${@}"
